development:
  adapter: mysql2
  database: test
  host: localhost
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: utf8
production:
  adapter: mysql2
  database: test
  host: localhost
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: utf8
test:
  adapter: mysql2
  database: test
  host: localhost
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: utf8
